### PR TITLE
110 update navbar buttons

### LINKED ISSUE #110: [Frontend] Update Navbar styles
**Task**
Update navbar styles (client/src/components/Navbar)
***After #109 is merged***

**More about the task (optional)**
Signup button = size changes on hover, it should stay the same
Style logged in navbar

image

**Alternatives you've considered (optional)**

**Additional context (optional)**

### PR DESCRIPTION
**Pull request by devrisby**
## Summary

As per issue #110, I added `min-width` to prevent the sign up and login buttons from expanding and I added styling to the logout button

Closes #110 

image

It's been a while since I did any CSS 😅, so please provide any feedback

Thank you!

### CODE REVIEW

**Comment by devrisby** [comment]
oh shoot, the tests failed 

I think I know how to fix 2 of the failing tests...I changed the button text `Logout` to `Log Out` as per the screenshot in #110 

I bet if I were to change it back to `Logout`, 2 of the failing tests should pass
Not sure about the 3rd one...

I'll do this tomorrow (20 hours from now)

image

**Comment by cherylli** [comment]
yeah i think the design is "Log Out" we should just change the tests. Do you want to do it? if not I can

**Comment by devrisby** [comment]
> 

Oooh, let me do it. I never worked with Cypress before, so this will be a good opportunity

Thanks! I think I can get this done in 1 or 2 days (resolving the failed tests)

**Review by cherylli — COMMENTED** [review]
looks good. Thanks for adjusting the tests. Everythings working, but all the buttons (sign up, log in and log out) have the same style so I would just use the same styles for all of them and make minor adjustment for "login" which has a different colour for example.

**Comment by devrisby** [comment]
> looks good. Thanks for adjusting the tests. Everythings working, but all the buttons (sign up, log in and log out) have the same style so I would just use the same styles for all of them and make minor adjustment for "login" which has a different colour for example.

can you clarify what you mean? I can understand using the same styles for all the buttons. But I think the issue I had was that the signup/login buttons were actually `<li>` items instead of buttons. I don't remember exactly, but I think I had to use some different values to make things look "consistent" across all the "buttons"

**Comment by cherylli** [comment]
oh yeah they are different because Log out is something I added temporarily, but it would be better to make all the "buttons" consistent. 

We can re visit this issue later, I think it will require some refactoring of the JSX

**Review by cherylli — APPROVED** [review]

**Comment by cherylli** [comment]
@devrisby, It seems changing the log out button to Navlink works, so we should be able to use the same styles for all of them.

If you would like to refactor it, please do another pull request, otherwise I'll do it next time  🙂

**Comment by devrisby** [comment]
> @devrisby, It seems changing the log out button to Navlink works, so we should be able to use the same styles for all of them.
> 
> If you would like to refactor it, please do another pull request, otherwise I'll do it next time 🙂

That's a great idea. I hadn't realized that I could've just changed the button to `li` tag.    I'll work on it then. I think I'll get it done in 1 or 2 days

**Pull request merged**
