### PR TITLE
Add two endpoints : /api/users/signup  & /api/users/login in docs.yaml

### PR DESCRIPTION
**Pull request by EleekaN**
Hi, I am new to swagger documentation and this platform.
I am trying to do it right the first time but I am sure there will be some scope of improvements. 
Please share your feedback and I will make the necessary changes. 

I have updated the endpoints in the docs file.

### CODE REVIEW

**Comment by cherylli** [comment]
Hi, thank you for your pull request. Did you use npm instead of yarn? as you have generated an extra file, package-lock.json

**Comment by EleekaN** [comment]
Hi Cheryl,

Yes, I had used npm....sorry for the confusion.

**Comment by cherylli** [comment]
could you please redo it with yarn? Thank you. You should be able to just copy and paste the changes you did in the yaml file

**Comment by EleekaN** [comment]
@cherylli I don't know how to use yarn...may be I can try some google search on how to use it
I will try to rewrite the yaml file again.
Is there a way to try the API live to understand the response codes for those endpoints?
thank you.

**Comment by cherylli** [comment]
You can follow these instructions here to run the server locally,
https://github.com/webdev-20/shorti-url-shortener/blob/main/CONTRIBUTE.md#how-to-run-the-project-locally

It is also hosted here on render 
https://shorti-server.onrender.com/

**Comment by EleekaN** [comment]
Hi @cherylli , having some issues with yarn, I was thinking if updating the yaml file would do the work without running yarn,

**Comment by cherylli** [comment]
yeah probably ok but would be good if you can run it locally to test that everything is working.

what issues are you having with yarn? you probably have to delete node_module and all the npm related files and re run `yarn install`

**Comment by EleekaN** [comment]
I installed yarn and then gave the command - yarn start....it runs fine but later I get a long error message which begins with--- 
TypeError- JwtStrategy requires a secret or key....

**Comment by cherylli** [comment]
you'll need to create a .env file in /server/

put this in the .env file,

JWT_SECRET=<any string>

you might also need MONGO_URI=

if so you can register for a mongo atlas account and a mongo atlas connection string, following this https://www.techomoro.com/connect-mongodb-atlas-with-express-backend/

**Pull request closed without merging**
