### PR TITLE
MyProfile API added, authentication middelware

### PR DESCRIPTION
**Pull request by harshilsharmaa**
## Summary
API to get the logged In user profile.
## Checklist
- If user is logged In the he/she will able to see their profile and all links made by them.
- Middleware to check authentication (logged In or not).

[upload the screenshot here] (optional)

Untitled Diagram drawio (1)

### CODE REVIEW

**Comment by harshilsharmaa** [comment]
Please review this.

**Comment by cherylli** [comment]
have you tested locally? Will this work when the link collection is not yet connected to the user? Please post screenshots showing it's working
Also, do you mind resolving all the conflicts? So I can pull and have a look, thank you

**Comment by harshilsharmaa** [comment]
Yes, it is tested,
dev1

And for linking links, it can be done by this way:
- If user is logged in and creating new link than at that time the reference of that link suppose to be added in "link" array in user model.
- For checking if user is logged in we can use another middleware and put current user in "req.user" else it will remain "undefined".
- And on creating new link we can check if (req.user) , if it is than we add that link id to user's link array.
it will look like this 👇 
(in create link function)
dev02

otherwise just create link if there is no user logged in.

**Comment by cherylli** [comment]
close - inactive/unresolved conflicts

**Pull request closed without merging**
