### PR TITLE
add auth endpoints

### PR DESCRIPTION
**Pull request by EleekaN**
## Summary
added specifications for two endpoints:
/api/users/signup
/api/users/login
- checked in editor.swagger.io

### CODE REVIEW

**Comment by EleekaN** [comment]
HI @cherylli, I tried out those two endpoints in swagger editor. It was looking fine. Please review it. Thank you.

**Comment by cherylli** [comment]
Hi, thanks for doing this. It looks good but could you also add the response content like this please?

image

**Comment by EleekaN** [comment]
Sure, so you want these sample response for authorization endpoints, right?

**Comment by cherylli** [comment]
They need to match the code. The screenshot was an example. Thank you. 🙂

**Comment by EleekaN** [comment]
> They need to match the code. The screenshot was an example. Thank you. 🙂

right... understood, thank you :-)

**Comment by EleekaN** [comment]
I made the changes but I don't know how to link the updated file here.

**Comment by cherylli** [comment]
> Trying to update the file here. Should I create a new PR?

@EleekaN no, you don't have to make a new pr, you can just push the new changes to the same branch and it will reflects in the old pr

**Pull request closed without merging**
